# Generated by Django 4.2.1 on 2023-05-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='Ninguna', max_length=32),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
