# Generated by Django 4.2.1 on 2023-05-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0002_remove_orden_productos_remove_orden_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default='image not found', max_length=200),
        ),
    ]
